### ISSUE TITLE
I followed the steps provided but localhost:8000 is Server error

### ISSUE THREAD

**Issue by johnfrades** [nicholashamilton/laravel-react#3]
any idea on how to fix this?

After doing the composer and npm install, i've tried npm run dev, go to localhost:8000, its giving me 500 | server error,
but the API route http://localhost:8000/api/v1/example is working, i can get the response @nicholashamilton

**Comment by nicholashamilton** [comment]
Hello @johnfrades, this can occur if you haven't set up the `.env` file from the `.env.example`.

Try running `cp .env.example .env` and see if that fixes the 500 error.

Let me know if that resolves your issue.

**Comment by johnfrades** [comment]
Thanks it worked @nicholashamilton !
