### ISSUE TITLE
Deployment on Railway

### ISSUE THREAD

**Issue by alucard079** [nicholashamilton/laravel-react#8]
Hello, I really appreciate this boilerplate. May I ask if you have some YouTube or tutorial, how can I deploy this using `Railway`. Thank you!

**Comment by nicholashamilton** [comment]
Hey @alucard079, glad you like it. 

I've never deployed a Laravel Application to Railway before. I might try it out sometime and create a blog post documenting my findings.

I use AWS EC2 + RDS as my primary deployment strategy for Laravel, i'm also thinking of writing a blog post on that as well.

**Railway Docs Laravel**: https://railway.app/template/fWEWWf
**Invariance**: https://invariance.dev/2022-08-04-deploy-laravel-on-railway.html
**Youtube Tutorials**:
https://www.youtube.com/watch?v=1Jmqj0IsyhQ
https://www.youtube.com/watch?v=Opxn-X8eX_0
